### ISSUE TITLE
Add Volume control for polyrythms.py

### ISSUE THREAD

**Issue by Vaarun-C** [acmpesuecc/satisfying-visualizations#2]
Currently, the only way to control audio for the application is to control the system's audio.

Windows and Linux have application-based volume control. But on mac its not possible without 3rd party tools...

So can you try to implement this feature in the python script? Have like a slider to control the audio output

**Comment by SlimShady1414** [comment]
Can i be assigned to this?

**Comment by Vaarun-C** [comment]
Sure! Goodluck :)

**Comment by atharvakinage** [comment]
can i be assigned to this issue

**Comment by Vaarun-C** [comment]
Sorry!, But only open assignee per issue

**Comment by Vaarun-C** [comment]
!bounty 25
