### ISSUE TITLE
Fix collision issues in box.py

### ISSUE THREAD

**Issue by Vaarun-C** [acmpesuecc/satisfying-visualizations#3]
The box.py script does not handle collision properly.
![image](https://github.com/Vaarun-C/satisfying-visualizations/assets/65110122/0f0ab9fa-2602-4742-a265-a7f10457197b)

### Expected Behavior
The box remains completely inside the white square even during collisions

### Actual Behavior
The box overshoots the white square

**Comment by pushkar-gr** [comment]
Yo can I ?

**Comment by Vaarun-C** [comment]
One issue at a time

**Comment by tejas-techstack** [comment]
can i get assigned please

**Comment by Vaarun-C** [comment]
Sure thing all the best :)

**Comment by aniruddhajoshi100** [comment]
hey can i get assigned to this?

**Comment by Vaarun-C** [comment]
> can i get assigned please

@tejas-techstack are you still working on this?

**Comment by aniruddhajoshi100** [comment]
he removed his assignment, can i get it now?

**Comment by amrit-george** [comment]
can i be assigned this issue?

**Comment by NJWasTaken** [comment]
Can I be assigned?

**Comment by Vaarun-C** [comment]
> Assign me to this please

Go ahead @LalithaTanmayee

**Comment by LalithaTanmayee** [comment]
I'm having dinner, sorry
pls assign to the next person

**Comment by aniruddhajoshi100** [comment]
so can i get assigned to this?

**Comment by C-VISHWA** [comment]
hi
can i get assigned to this 
i even have the code ready

**Comment by Vaarun-C** [comment]
@LalithaTanmayee can you show me some progress by 10:15?
or I'll be forced to assign someone else

**Comment by BizBrainiac** [comment]
can i get this?

**Comment by Vaarun-C** [comment]
> hey can i get assigned to this?

go ahead @aniruddhajoshi100

**Comment by siri-n-shetty** [comment]
Could you please assign this to me?

**Comment by Python-is-better-than-Java** [comment]
Can I be assigned this?

**Comment by ssether04** [comment]
can i get assigned if this is still open?
