### ISSUE TITLE
Add sounds for box.py

### ISSUE THREAD

**Issue by Vaarun-C** [acmpesuecc/satisfying-visualizations#4]
As in the [Project jdm video](https://www.youtube.com/shorts/JA-7nvt-JJs), add sound effects for:

- Collisions with the white box
- Each time a new box is printed on the screen
- Feel free to add any more sound effects that you think will be fun :)

**Comment by Prashantradder** [comment]
can I ?

**Comment by Vaarun-C** [comment]
Sure thing all the best :)

**Comment by kavs2803** [comment]
can i be assigned?

**Comment by Vaarun-C** [comment]
Sorry!, But only open assignee per issue

**Comment by Vaarun-C** [comment]
@Prashantradder it has been more than half an hour, Can you please show me some progress
Otherwise, I will be forced to unassign you

**Comment by sjp-codes** [comment]
can i be assigned to this?

**Comment by Hiyanachnani** [comment]
hiii i would like to work on this please assign it to me

**Comment by aniruddhajoshi100** [comment]
hey can i get assigned to this?

**Comment by Vaarun-C** [comment]
> can I ?

are you still working on this? @Prashantradder

**Comment by kavs2803** [comment]
can i be assigned to this now?

**Comment by Archit-Rode** [comment]
Can i be assigned to this

**Comment by Vaarun-C** [comment]
@Prashantradder can you show me some progress by 10:15? Or I''ll be forced to assign someone else

**Comment by siri-n-shetty** [comment]
Could you please assign this to me?

**Comment by PandaTGOS** [comment]
can I get assigned ?

**Comment by Vaarun-C** [comment]
> can i be assigned?

go ahead @kavs2803

**Comment by kdb04** [comment]
can i be assigned?

**Comment by BizBrainiac** [comment]
can i get this...?

**Comment by ssether04** [comment]
can i get assigned if this is still open?

**Comment by BizBrainiac** [comment]
@Vaarun-C bro can i get i kinda finished it pls assign it to me

**Comment by ankitam389** [comment]
can i pleeease get assigned to this task??

**Comment by aniruddhajoshi100** [comment]
can I get this if still open?

**Comment by C-VISHWA** [comment]
can i get it assigned if its still available 
i have the code 
(i even fixed the collision issues)
