### ISSUE TITLE
Random starting positions for box.py

### ISSUE THREAD

**Issue by Vaarun-C** [acmpesuecc/satisfying-visualizations#5]
Currently, the box in box.py always starts at the bottom-left corner. It would be more interesting if the box started from random positions within the white box area :).

**Comment by Shaatvika** [comment]
Can I get assigned?

**Comment by Vaarun-C** [comment]
Sure thing all the best :)

**Comment by Nightwing000** [comment]
can i get assigned

**Comment by Vaarun-C** [comment]
Someone is already working on this issue... feel free to chose others :)

**Comment by 825pranav** [comment]
hey can I be assigned to this?

**Comment by Vaarun-C** [comment]
> hey can I be assigned to this?

Someone is already working on this issue... feel free to chose others :)

**Comment by Shaatvika** [comment]
Please reassign it to me

**Comment by Vaarun-C** [comment]
@Shaatvika 
it has been more than half an hour, Can you please show me some progress
Otherwise, I will be forced to unassign you

**Comment by Vaarun-C** [comment]
@aniruddhajoshi100 You Have been assigned to this issue, Happy Coding!

**Comment by shakirth-anisha** [comment]
can I be assigned to this??
