### ISSUE TITLE
Add volume control for box.py

### ISSUE THREAD

**Issue by Vaarun-C** [acmpesuecc/satisfying-visualizations#6]
Currently, the only way to control audio for the application is to control the system's audio.

Windows and Linux have application-based volume control. But on mac its not possible without 3rd party tools...

So can you try to implement this feature in the python script? Have like a slider to control the audio output

**Comment by pushkar-gr** [comment]
Can I ?

**Comment by Vaarun-C** [comment]
Sure thing man :)

**Comment by atharvakinage** [comment]
can i be assigned to this issue

**Comment by Vaarun-C** [comment]
Sorry!, But only open assignee per issue

**Comment by Vaarun-C** [comment]
@pushkar-gr it has been more than half an hour, Can you please show me some progress
Otherwise, i will be forced to unassign you

**Comment by likhitharigela** [comment]
Can i get Assigned to it pls

**Comment by Vaarun-C** [comment]
> Can I ?

@pushkar-gr are you still working on this?
can you show me some progress?

**Comment by Vaarun-C** [comment]
> can i be assigned to this issue

Ok go ahead @atharvakinage

**Comment by Vaarun-C** [comment]
Can you give me some progress by 10:15 @atharvakinage ? Or I'll be forced to assign someone else

**Comment by atharvakinage** [comment]
yes give me 5 mins

**Comment by ManushriJ** [comment]
can i get assigned to this?

**Comment by akdino** [comment]
can i get assigned to this pls?

**Comment by likhitharigela** [comment]
@Vaarun-C  Can u assign it to me .. I got the required output

**Comment by ProSai8055** [comment]
can you assign me

**Comment by ssether04** [comment]
can i get assigned if this is still open?

**Comment by Vaarun-C** [comment]
Sure thing @likhitharigela

**Comment by DedLad** [comment]
giv

**Comment by PandaTGOS** [comment]
Can I get assigned to this ?

**Comment by Vaarun-C** [comment]
@ProSai8055 @ssether04 and @DedLad  do you wanna work on this issue?

Or I'll transfer this to @PandaTGOS

**Comment by Vaarun-C** [comment]
@PandaTGOS go ahead

**Comment by PandaTGOS** [comment]
Ok pull request-ing again
